sourceCompatibility = 1.8
targetCompatibility = 1.8

version = "2.2.0"
group = "de.pfannekuchen.lotas"
archivesBaseName = "lotas"

repositories {
	maven { url 'https://maven.mgnet.work' }
	maven { url 'https://jitpack.io' }
    mavenCentral()
}

configurations {
	include
	implementation.extendsFrom(include)
}

dependencies {
	implementation 'org.projectlombok:lombok:1.16.4'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.6.21'
    include 'com.google.code.findbugs:annotations:3.0.1u2'
    modImplementation "net.fabricmc:fabric-loader:0.12.12"
}

tasks.matching { it.name == 'compileKotlin' || it.name == 'compileTestKotlin' }.configureEach {
    def javaTarget = project.targetCompatibility.toString()
    if (javaTarget == '8') {
        javaTarget = '1.8'
    }
    kotlinOptions.jvmTarget = javaTarget
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

build.dependsOn processResources
defaultTasks 'build'

jar {
	from {
    	configurations.include.collect { it.isDirectory() ? it : zipTree(it) }
  	}
  	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

if (project.name != 'fabric') {
    apply from: '../preprocessor.gradle'

    def preprocessedSrc = 'build/preprocessed/src'
    def preprocessedKotlin = 'build/preprocessed/kotlin'
    def preprocessedRes = 'build/preprocessed/res'
    def originalSrc = '../../src/main/java'
    def originalKotlin = '../../src/main/kotlin'
    def originalRes = '../../src/main/resources'
    def (major, minor, patch) = project.name.tokenize('.')
    def mcVersion = "${major}${minor.padLeft(2, '0')}${(patch ?: '').padLeft(2, '0')}"
    def vars = [MC: mcVersion as int]

    sourceSets {
        main.java.srcDir preprocessedSrc
        main.kotlin.srcDir preprocessedKotlin
        main.resources.srcDir preprocessedRes
    }

    task preprocessJava {
        inputs.dir(originalSrc)
        outputs.dir(preprocessedSrc)
        doLast {
            project.convertTree(vars, originalSrc, preprocessedSrc)
        }
    }

    task preprocessResources {
        inputs.dir(originalRes)
        outputs.dir(preprocessedRes)
        doLast {
            project.convertTree(vars, originalRes, preprocessedRes)
        }
    }

    task preprocessKotlin {
        inputs.dir(originalKotlin)
        outputs.dir(preprocessedKotlin)
        onlyIf {
            file(originalKotlin).exists()
        }
        doLast {
            project.convertTree(vars, originalKotlin, preprocessedKotlin)
        }
    }

    compileJava.dependsOn preprocessJava
    compileKotlin.dependsOn preprocessJava
    compileKotlin.dependsOn preprocessKotlin
    processResources.dependsOn preprocessResources
}
