plugins {
	id 'fabric-loom' version '1.1-SNAPSHOT'
	id 'org.jetbrains.kotlin.jvm' version '1.6.21'
	id 'org.jetbrains.kotlin.plugin.serialization' version '1.6.21'
}

apply from: '../common.gradle'
archivesBaseName = "LoTAS1.16.1"

loom {
	accessWidenerPath = file("../../src/main/resources/lotas.accesswidener")
}

dependencies {
	minecraft "com.mojang:minecraft:1.16.1"
	mappings loom.officialMojangMappings()
}